# CLIP VIDEO FILE WITH START_SECONDS TIME AND CLIP DURATION_SECONDS

FILE=$1
START_SECONDS=$2
DURATION_SECONDS=$3
OUTPUT="CLIP_"$FILE
ffmpeg -ss $START_SECONDS -i $FILE -t $DURATION_SECONDS -c copy $OUTPUT
